### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by kynan** [citation-style-language/zotero-bits#35]
BibTeX know the item type "manual", which in particular does not require an author to be given and provides the additional optional fields organization, address, edition ( and month, year, note). I'd like to see that reflected by an item type in zotero.

Currently I use Document for this purpose, but this is translated to BibTeX as type Misc, which is not a very good match.

When no author is given, zotero generates a BibTeX key starting with an _ which LaTex does not accept.

**Comment by bwiernik** [comment]
@retorquere Does BBT have any special behavior for `@manual` like it has for `thesis`? Is this something that a BBT-like translator could handle?

From a citation generation perspective, I don't see a need to distinguish manual and report.

**Comment by retorquere** [comment]
Do you mean for import, or for export? For export, `tex.referencetype: manual` will do the trick, but I think it'd be reasonable to export a report with the `type` field set to `manual` as `@manual`.

**Comment by retorquere** [comment]
Is `report` a better choice for manual import than `book`?

**Comment by bwiernik** [comment]
Yes, I think so. And agree about export with `type` set to `manual` (or containing `manual`).

**Comment by retorquere** [comment]
Would that be for both bibtex and biblatex?

**Comment by bwiernik** [comment]
Yes. Both bibtex and biblatex have `@manual` separate from `@techreport` or `@report`.

**Comment by retorquere** [comment]
I have `@manual` entries in my test suite that have an `edition` field; Zotero `report`s don't seem to have an equivalent, where `book`s do.

**Comment by bwiernik** [comment]
That should go in Extra. Report is a better match for manuals and what we’ve been recommending on the Zotero forums for a while.

**Comment by retorquere** [comment]
Alright, that's what it does now. I'll commit it to master, together with the change for import.

**Comment by bwiernik** [comment]
I think this can be closed.

**Comment by stefanct** [comment]
It is not better because techreports require an author value. Most reference manuals are published by institutions/companies. And that should go into the organization field of manual entries but is put into institution if the tex.referencetype: manual trick is used which is not valid for manuals at all.
So one has to not only set the tex.referencetype but also use a script to fix that, something like the following. i prefer the institution in the author field, if none is set, because some styles duplicate the organization in that case (in the front as replacement for the author and then again as the organization).

    if (Translator.BetterTeX) {
      if (item.extra) {
        if (item.itemType == 'report') {
          if (entry.entrytype == 'manual') {
            if (item.publisher) {
              if (item.author) {
                entry.add({ name: 'organization', value: item.publisher });
              } else {
                entry.add({ name: 'author', value: item.publisher, enc: 'literal' });
              }
              entry.remove('publisher')
            } else {
              Zotero.debug("No institution for " + item.citationKey);
            }
          }
        }
    }

**Comment by retorquere** [comment]
@stefanct can you open an issue for this on the BBT repo?

**Comment by stefanct** [comment]
https://github.com/retorquere/zotero-better-bibtex/issues/2083
