### ISSUE TITLE
differentiate conference contributions: proceedings, slide show, poster

### ISSUE THREAD

**Issue by wilfriedh** [citation-style-language/zotero-bits#51]
Up to now there is only the item type "Conference Paper". 
Now consider 
- A manuscript has to be submitted to the program committee. This manuscript may also be published as preprint on the author's website. 
  The item type "manuscript" has the field "Type:" which may contain "paper submitted to ..." which is correctly inserted with the APA style.
- The committee decides whether the manuscript is rejected, or accepted as oral presentation, or accepted as poster presentation. 

So there are four types of possible conference contributions:
- If proceedings are published, the text printed in the proceedings. This matches the current item type "Conference Paper", which is called "Conference Proceedings" in Endnote and "CONF" in RIS.
- If no proceedings are published, but the text e.g. supplied as a handout at the conference, this would match the item type "Conference Paper" in Endnote and "CPAPER" in RIS, but has no match in Zotero.
- If accepted as oral presentation, the slide show presented.
- If accepted as poster presentation, the poster presented.

How to store and cite the last three? 
"Conference Paper" in Zotero does not have the field "Type". 
"Presentation" is supported in none of the default styles and inconsistently in some translators, e.g. in ReferBibIX.js it maps to "report", in RDF.js it maps to "event". Moreover, in CSL it maps to "speech", see http://gsl-nagoya-u.net/http/pub/csl-fields/index.html .

The differentiation could either be achieved by activating the "Type" field for conferencePaper - however the current formatting for conferencePaper matches printed proceedings, which often have an ISBN/ISSN, a publisher, a place published, and are available from libraries, and does not match the other types which are most often only available online or from the author.
Or it could be achieved by adding more item types.
I am not sure what would be better, so, please, comment on this.

**Comment by bwiernik** [comment]
Any of the three examples that are not published in a proceedings should be cited as a Zotero Presentation/CSL speech.
