### ISSUE TITLE
Cartographer Creator Type

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/zotero-bits#58]
Not sure if this is important enough. It's required in Vancouver as a minimum
http://www.nlm.nih.gov/bsd/uniform_requirements.html no. 32
Forum thread here: https://forums.zotero.org/discussion/29335/how-to-add-cartographers-in-bibliography/#Item_4
Zotero already has a cartographer creator type, this would entail adding it to CSL and mapping.

For Vancouver alone this is probably not worth it, but if it's also common in geography/geology it likely would be @bdarcus - as the resident geographer: Thoughts?

**Comment by bwiernik** [comment]
In a perusal of major geography, geosciences, public health, and epidemiology journals, I see no requirements for a special format for maps/cartographers. I think we can safely map cartographers to `author` and at most, create a `cartographer` term that could be added ala https://github.com/citation-style-language/csl-evolution/issues/33

**Comment by denismaier** [comment]
There's no need for a CSL change, right? If so, could you @bwiernik add the Zotero label and remove the CSL-change?

**Comment by bwiernik** [comment]
The change would be something to let Zotero or users add the "Cartographer" term to a name. Keeping the label there until I can put a pull request together for that.

**Comment by bwiernik** [comment]
I looked through several different cartography, geography, and GIS journal guidelines. None call for labeling cartographers differently from other types of authors, so I suggest passing over this until we get any more requests than that one from 9 years ago.
