### ISSUE TITLE
Location field in "artwork" type for architecture, sculpture and other site-specific art?

### ISSUE THREAD

**Issue by cloo** [citation-style-language/zotero-bits#66]
I'm collecting data about architectural, sculptural, graffiti and oher site-specific objects, where location record is a crucial. For now I'm forced to use quite irrelevant "Report" field only because it has a "Place" field. 
I suggest to add location field to  "Artwork" type.

**Comment by gracile-fr** [comment]
Related to https://github.com/citation-style-language/zotero-bits/issues/26
