### ISSUE TITLE
Term for every item type

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/zotero-bits#70]
It's not going to get us a comprehensive list, which will never be possible, but this will get us a lot closer to localizing styles like MLA or APA that include a lot of descriptive terms  ([Date set] [sound recoding] etc.) in bib entries.

**Comment by zuphilip** [comment]
As a start we could use the translated item types from Zotero.

**Comment by bwiernik** [comment]
Could this set of terms get special treatment so that it can be called with something like `term="item-type"` or `term="type"` and then have the correct term generated based on the item type? This would make coding things like fallback rules for APA or MLA much shorter.

**Comment by adam3smith** [comment]
I definitely see the appeal of that, but I'm worried that it'll slow down implementation. @zuphilip and I went through things that we thought could be implemented without any processor changes beyond updating variables/types/terms and were fairly uncontroversial and labeled them with the 1.2 milestone. 

I think adding a term with a special logic should go into CSL 2.0, since it requires new functionality and syntax.

**Comment by bwiernik** [comment]
Okay, that's fine. Easy enough to update styles at that point.

**Comment by cormacrelf** [comment]
Nah, implementation is easy, just a single extra hash lookup. Go for it.

(Yes, I’m working on a processor.)

**Comment by denismaier** [comment]
I suggest we move this to "Accepted". Ok?

**Comment by bwiernik** [comment]
@denismaier Note specifically the special treatment of `term="type"` by processors I mention above.

**Comment by denismaier** [comment]
@bwiernik Thanks for reminding me of your suggestion. @adam3smith had some concerns we should discuss first, but I'd rely on @cormacrelf's judgement here. If it's that simple I don't see why I should not be done.
 
Anyway, I've created a [new issue in the evolution repo](https://github.com/citation-style-language/csl-evolution/issues/17), and discussion should probably take place there.

**Comment by bwiernik** [comment]
Closing this here to continue discussion in the other repo.
