### ISSUE TITLE
Web Page Creation Issue

### ISSUE THREAD

**Issue by MrSlosberg** [citation-style-language/zotero-bits#71]
Zotero, v4.0.29.15 on the MacBook Pro iOS, v10.12
Web Page does not appear as a type under New Item
Under Item Type it can be changed to a Web Page (current workaround)

**Comment by karnesky** [comment]
This tracker is for the citation style language, not for the general Zotero interface. That being said, the lack of a webpage type in the dropdown was a methodical decision so that people would use the 'Create Web Page Item from Current Page' function.

Closing this.

**Comment by MrSlosberg** [comment]
Thank you for your explanation.

**Comment by rmzelle** [comment]
@MrSlosberg, for more detail, see https://forums.zotero.org/discussion/62704/bug-report-user-interface-file-new-item-web-page.

(and as @karnesky kindly remarked, it's usually best to report anything Zotero-related to the Zotero forums)
