### ISSUE TITLE
Web Page Publisher

### ISSUE THREAD

**Issue by MrSlosberg** [citation-style-language/zotero-bits#72]
Web Page does not have a field for “Publisher” although Document does
http://occ.ibo.org/ibis/occ/home/subjectHome.cfm?subject=eeyyy
For the above source, the publisher (IBO) is required by the MLA style, but cannot be entered.  I have tried converting to document, adding “Publisher” and converting back, but the “Publisher” information gets lost.

**Comment by karnesky** [comment]
Similar to #71, this is not the venue to discuss this. By I believe this is in the list of fields to add when the database schema is changed. Closing.

**Comment by MrSlosberg** [comment]
Do I need to post it to the list of fields to add, or is it already there?

-----------------------------------------------------------------------------------------------------
Mr. Slosberg
Teacher of Math, Physics, and German

"Never doubt that a small group of thoughtful, committed citizens can
change the world; indeed, it's the only thing that ever has." Margaret
Mead

**Comment by karnesky** [comment]
This is redundant to #30. You don't need to do anything. If you have other issues with zotero, you may be better off starting a thread at forums.zotero.org

**Comment by MrSlosberg** [comment]
Ok.  Thank you for your help.

-----------------------------------------------------------------------------------------------------
Mr. Slosberg
Teacher of Math, Physics, and German

"Never doubt that a small group of thoughtful, committed citizens can
change the world; indeed, it's the only thing that ever has." Margaret
Mead

**Comment by rmzelle** [comment]
@MrSlosberg, so yes, we're planning to recommend this particular change to the Zotero developers. It might take a while, though, since it's currently not easy to add or change fields in Zotero.
