### ISSUE TITLE
Support for illustrator creators field in Zotero 5?

### ISSUE THREAD

**Issue by mvolz** [citation-style-language/zotero-bits#75]
Hi,

I notice CSL does have an illustrator creators field, but this isn't supported currently in Zotero... is there a reason for this? Any chance of getting it? (Not sure this is really the right place?)

**Comment by rmzelle** [comment]
> I notice CSL does have an illustrator creators field, but this isn't supported currently in Zotero... is there a reason for this? Any chance of getting it?

Yes, so CSL introduced an "illustrator" variable in CSL 1.0.1 (released in 2012), but the small team of Zotero developers have been unable for the past few years to make any changes to the fields and item types Zotero provides. That should finally change once Zotero 5.0 is released (which has completely overhauled sync code), which, fingers crossed, should be any day now. After that, we can advocate to get "illustrator" as a contributor field in e.g. Zotero 5.1 or 5.2.

So it's still planned, and there is some recent movement on the issue.

See also https://github.com/citation-style-language/zotero-bits/issues/47
