### ISSUE TITLE
Remap Podcast to broadcast

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/zotero-bits#83]
At least in its contemporary usage, podcasts are much more similar to radio broadcasts than they are to musical recordings, especially in terms of citation requirements (specific dates, serialization, etc.). In Zotero, it would be good to remap **podcast** to `broadcast` rather than to `song` as it is now.

**Comment by dstillman** [comment]
Closed in https://github.com/zotero/zotero/commit/bf4deeff8fb94fff253a1a47d2cff94f9f4fba9c

**Comment by dstillman** [comment]
After making this change, a podcast item exported to CSL JSON includes `collection-title` for the Series Title, but the item is reimported as TV Broadcast and that field is lost. I assume there's nothing to do about that now, but should Series Title be added to TV Broadcast? I didn't see that in a quick glance at the open issues.

**Comment by bwiernik** [comment]
No, Series Title for Podcast should be remapped to `container-title`. It is analogous to the Program Title field for TV Broadcast.

**Comment by dstillman** [comment]
Hmm, is that right? That's a bit problematic if so. Series Title and Program Title aren't equivalent fields in Zotero. Series Title is just Series Title, and it exports to `collection-title` from any item type. Program Title is a base-mapped field for Publication Title, which gets exported as `container-title`.

**Comment by bwiernik** [comment]
The choice of fields generally for Podcast don’t make much sense. There is no field for “Program Title” of the podcast as a whole, rather than the episode (analogous to TV Broadcast).

Series Title doesn’t make much conceptual conceptual sense for TV Broadcast or Podcast. It would be the name for a collection of related episodes within the broader Program Title (e.g., perhaps the name of a five-episode arc or special report). I’m not sure that these are common enough to warrant a field. If they are included “Series Title” is a very confusing label for that—I imagine most users would not know what the difference between “Program Title” and “Series Title” would be.

**Comment by dstillman** [comment]
OK, so it would be better to just migrate seriesTitle to programTitle in podcast?

**Comment by bwiernik** [comment]
Yes.
