### ISSUE TITLE
Map date field as year

### ISSUE THREAD

**Issue by darkdragon-001** [citation-style-language/zotero-bits#86]
Please make the published `year` available via BibTeX. Currently it is stored in the field `date` from which it can be extracted. Item types are written sources like `Conference Paper` and `Book`. 

I am using the exported bibliography in Overleaf (which is using _Web Exporter API_).

**Comment by karnesky** [comment]
Isn't this functionality available already in both CSL and in Zotero?
In the former, see, e.g. [BibTeX.csl](https://github.com/citation-style-language/styles/blob/master/bibtex.csl): 
`  <macro name="issued-year">
    <date variable="issued">
      <date-part name="year"/>
    </date>
  </macro>`

**Comment by darkdragon-001** [comment]
@karnesky I am new to Zotero internals. Fact is, that I add items in Zotero, fill in the `Date` field and in my Overleaf BibTeX file, only a field `date` appears, but no field `year`. 

I asked Overleaf support and got the following answer:

> Overleaf's Zotero importer uses Zotero's Web Exporter API, which does not quite behave the same as the Zotero Desktop exporter, although both are developed and maintained by Zotero. Unfortunately at present, we aren't able to set any options or change the output generated by the Zotero Web Exporter API; i.e. the Zotero importer just takes the output as-is, and adds it to an Overleaf project.

How should I continue my investigation to fix the issue?

**Comment by karnesky** [comment]
This sounds like an Overleaf issue, but I'm not familiar with their tool.

The web-based Zotero API will export a 'year' when format=bibtex and will export a 'date' when format=biblatex.

This seems to be correct behavior for those two export formats.

**Comment by adam3smith** [comment]
Yes, what @karnesky says. Overleaf used to allow you to choose between biber/biblatex and bibtex when auto-importing from Zotero, so make sure you have the latter selected, but Zotero is doing everything correctly here. Closing.
