### ISSUE TITLE
Transfer to Zotero

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/zotero-bits#87]
At this point, I think we should transfer this repository to Zotero. @dstillman indicated they would like it for use as a checklist. The CSL side of it is done. Can someone with commit access to this repo potentially make that change? @rmzelle @bdarcus

**Comment by adam3smith** [comment]
The person transferring must have the rights to create a repository in the target org -- @dstillman I've given you admin for this repo -- I think that should be enough to transfer to Zotero, let me know if not.

**Comment by dstillman** [comment]
Thanks!
