### ISSUE TITLE
Please remove the Twitter handles from the author field

### ISSUE THREAD

**Issue by Mela** [citation-style-language/zotero-bits#90]
Since the last bigger update Zotero adds the Twitter handle in the author field if you pull a Tweet or thread with the Zotero browser extension into Zotero. 

This results in having to remove those Twitter handles by hand to get clean entries with authors ordered by "surname, prename".

Since this is the required format in most citation styles Zotero 6 breaks it. 

Having the Twitter handle in the author field also breaks the citations in Zettlr's PDF export.

Having the Twitter handle also present in a field in Zotero does make sense. But in the author field, it only causes trouble. 

Regards,
Mela

**Comment by bwiernik** [comment]
Please post requests like this to the Zotero forums. This repository is archived. 

Many citation styles, notably APA, do require the Twitter handle to be included in citations.
