### ISSUE TITLE
add field "lastaccessed" to type "webpage"

### ISSUE THREAD

**Issue by nata11** [citation-style-language/zotero-bits#91]
ACM (Association of Computing Machinery) publications[ BibTex formating guidlines ](https://www.acm.org/publications/authors/bibtex-formatting) show that [ACM BibTex Reference Format ](https://github.com/borisveytsman/acmart/blob/primary/ACM-Reference-Format.bst) uses the field "lastaccessed" instead of "accessdate". I use Overleaf to automatically sync my bibliography with Zotero libraries. But currently the export of BibTex or even BibLatex does not support the field "lastaccessed". So the last accessed date is not present in the final bibliography. Manual workaround is to use Better BibTex plugin and use a postscript like this to insert the field:

`if (Translator.BetterBibTeX && zotero.itemType === 'webpage') {
    if (zotero.accessDate) {
      tex.add({ name: 'lastaccessed', value: zotero.accessDate.replace(/\s*T?\d+:\d+:\d+.*/, '')});
    }
 }`

But this means bib files have to be synchronized manually to Overleaf. This is a feature request to add this field to any export, whether online or desktop versions.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
